blog/urls.py
from django.urls import path
from . import views

app_name = "blog"  # application namespace
# namespaces have to be unique across your entire project

# URL patterns allow you to map URLs to views
urlpatterns = [
    # post views
    path("", views.post_list, name="post_list"),  # function-based post_list view
    # the below class-based view instead of function-based
    # path("", views.PostListView.as_view(), name="post_list"),
    # in the following we use angle brackets to capture some parameters
    # since any value captured is by default string, we can convert them
    # with path converters the way shown below <int:year>
    path("<int:id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    # this is the path for our comment view
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    # path(
    #     "tag/<slug:tag_slug>/", views.PostListView.as_view(), name="post_list_by_tag"
    # ),  # in case of class-based post_list
    path(
        "tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"
    ),  # in case of function-based post_list view
]

# modifying urlpatterns to use publication date and slug for the post
# detail URL. This modification happens after understanding the concept
# of SEO-friendly canonical urls!
urlpatterns[1] = path(
    "<int:year>/<int:month>/<int:day>/<slug:post>/",
    views.post_detail,
    name="post_detail",
)


# all urlpattern are in form of a path
# with three arguments:
# 1.string pattern
# 2.a view
# 3.(optionally) a name that allows you to name the
# the URL pattern project-wide


# django runs through each URL pattern and stops at the first
# occurence that matches with a path

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# from django.conf.urls import include  # older version?

urlpatterns = [
    path("admin/", admin.site.urls),
    # local paths
    # with the following include from now on user will be directed
    # to blog's urlpatterns (behind the scene)
    path("blog/", include("blog.urls", namespace="blog")),
]

blog/models.py
# This includes the data models of your applications. All Django apps
# need to have a models.py file but it can be left empty.

from django.db import models
from django.utils import timezone

# very sophisticated user abstraction
from django.contrib.auth.models import User

# introduced for using canonical URLs
from django.urls import reverse

# from django.core.urlresolvers import reverse
# this is what I get for get_ab autocompletion

# for tagging our blogs (pip install django-taggit)
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    # my first model manager please use mngr snippet
    def get_queryset(self):
        return (
            super(PublishedManager, self)
            .get_queryset()
            .filter(status=Post.Status.PUBLISHED)
        )


# Create your models here.
class Post(models.Model):
    """Model definition for Post."""

    class Status(models.TextChoices):
        """an enumeration class for the post status
        with available choices DRAFT and PUBLISHED
        with their respective values DF and PB
        and their labels for readable name are
        Draft and published.
        """

        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    tags = TaggableManager()

    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )  # models.CASCADE ?!?!!??! What does it do?!

    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )

    title = models.CharField(max_length=250, null=False, blank=False)
    slug = models.SlugField(max_length=250, unique_for_date="published_on")
    # unique_for_date added since I decided to use slug for creating
    # canonical urls, so what's their point not being uniquely defined?
    body = models.TextField()

    created_on = models.DateTimeField(auto_now_add=True)
    published_on = models.DateTimeField(default=timezone.now)
    updated_on = models.DateTimeField(auto_now=True)

    # model managers for post
    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Our custom manager

    class Meta:
        """Meta definition for Post."""

        # verbose_name = "Post"
        # verbose_name_plural = "Posts"
        ordering = ["-published_on"]
        # Blog posts are usually displayed in reverse chronological order
        # (from newest to oldest)
        indexes = [
            models.Index(fields=["-published_on"]),
        ]

    def __str__(self):
        """Unicode representation of Post."""
        return self.title

    def get_absolute_url(self):
        """
        The reverse() function will build the URL dynamically using the
        URL name defined in the URL patterns. If check out blog/urls.py

        path("<int:id>/", views.post_detail, name="post_detail")

        We have used the blog namespace followed by a colon and the URL
        name post_detail. Remember that the blog namespace is defined in
        the main urls.py file of the project when including the URL
        patterns from blog.urls. The post_detail URL is defined above.
        The resulting string, blog:post_detail, can be used globally in
        your project to refer to the post detail URL. This URL has a
        required parameter that is id in this case.
        """
        return reverse(
            "blog:post_detail",
            args=[  # self.id,
                self.published_on.year,
                self.published_on.month,
                self.published_on.day,
                self.slug,
            ],
        )

    # def get_absolute_url(self):
    # # The canonical URL for a blog post detail view currently looks like /blog/1/
    #     from django.core.urlresolvers import reverse
    #     return reverse('blog:post_detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    """A Model to handle comments given to a post, which
    is a many to one relationship."""

    post = models.ForeignKey(  # type: ignore
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    # this related_name is funny! it allows us to name the
    # attribute that you use for the relationship from
    # related object back to this one

    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        """Meta definition for Comment."""

        ordering = ["created_on"]
        indexes = [
            models.Index(fields=["created_on"]),
        ]

    def __str__(self):
        """Unicode representation of Comment."""
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(
        max_length=25,
        label="Your Name:",
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "e.g. John Wick or Johnny",
                "size": "26",
            },
        ),
    )
    email = forms.EmailField(
        label="Your Email:",
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "johnwick@example.org",
                "size": "26",
            }
        ),
    )
    to = forms.EmailField(
        label="Recipient:",
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "oldmarrytodd@example.org",
                "size": "26",
            }
        ),
    )
    comments = forms.CharField(
        required=False,
        min_length=10,
        max_length=400,
        label="Comment:",
        disabled=False,
        widget=forms.Textarea(attrs={"placeholder": "What's on your mind?"}),
    )


class CommentForm(forms.ModelForm):
    """Form definition for Comment."""

    class Meta:
        """Meta definition for a comment form."""

        model = Comment
        fields = (
            "name",
            "email",
            "body",
        )

blog/views.py
# The logic of your application goes here; each view recieves an HTTP
# request, processes it, and returns a response

from django.shortcuts import render
from django.http import Http404
from django.shortcuts import get_object_or_404

# Now let's use some class-based views
from django.views.generic import ListView, DetailView

# Create your views here.
from .models import Post, Comment

# Making use of our forms
from .forms import EmailPostForm, CommentForm

# This one for sending emails
from django.core.mail import send_mail  # , send_mass_mail

# pagination is on the way
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# this is for comments' forms, we expect them to be submitted
# using HTTP POST method
from django.views.decorators.http import require_POST

# to utilize our tag system
from taggit.models import Tag


def post_list(request, tag_slug=None):  # my first view
    # posts = Post.objects.filter(status=Post.Status.PUBLISHED)
    # I use model manager created for published posts
    post_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    # Pagination with 3 posts per page
    paginator = Paginator(post_list, 5)
    page_number = request.GET.get("page", 1)
    # We retrieve the page GET HTTP parameter and store it in the page_number variable. This param-
    # eter contains the requested page number. If the page parameter is not in the GET parameters
    # of the request, we use the default value 1 to load the first page of results.

    # posts = paginator.page(page_number) # This commented for handling errors below

    # The following codes describe a way of handling errors
    # regarding our pagination
    try:
        posts = paginator.page(page_number)
    except EmptyPage:  # this way we can easily handle numbers that exceeds our pages
        # http://127.0.0.1:8000/blog/?page=-13
        if int(page_number) > paginator.num_pages:
            posts = paginator.page(paginator.num_pages)
        else:
            posts = paginator.page(1)
    # in case of not an integer number for pagination?
    except PageNotAnInteger:  # like http://127.0.0.1:8000/blog/?page=asdf
        posts = paginator.page(1)
    return render(
        request,
        "blog/post/list.html",
        {
            "posts": posts,
            "tag": tag,
        },
    )
    # we could also create a customised model manager
    # the default django's model manager is objects


# farewell to function-based views for now
# oopsie doopsie, back to it after playing around with tags


class PostListView(ListView):
    """
    Listing posts
    """

    queryset = Post.published.all()
    # Instead of defining a queryset attribute, we could have specified
    # model = Post and Django would have built the generic Post.objects.all()
    # QuerySet for us.
    context_object_name = "posts"
    paginate_by = 5
    # the above properties came from MultipleObjectMixin which is one the parents
    # of BaseListView (the other being View), which in turn, is one of the parents
    # of ListView (the other being MultipleObjectTemplateResponseMixin see below)
    template_name = "blog/post/list.html"
    # The daredavil who defined the above properties and might as well use it
    # is called TemplateResponseMixin which is the parent class of
    # MultipleObjectTemplateResponseMixin which in turn is one of the parents
    # of the class ListView (the other parent being BaseListView)

    def get_queryset(self):
        """
        In Django, when a class-based view is used, several methods are
        automatically called during the request/response cycle. One of
        these methods is get_queryset(), which is called internally by
        Django when you use a class-based view that inherits from ListView.

        When you provide a URL with a tag, such as /tag/tag-slug/, Django's
        URL routing mechanism will match the URL pattern defined in your urls.py
        file, which maps to the PostListView class-based view. The PostListView
        is then instantiated, and its get_queryset() method is called.

        In this case, the tag_slug is extracted from the URL using
        self.kwargs.get("tag_slug"). If a tag slug is present in the URL, the
        method retrieves the corresponding Tag object from the database and
        filters the queryset to include only posts associated with that tag.
        If no tag slug is present, all published posts are returned.

        By overriding the get_queryset() method, you can dynamically modify
        the queryset based on the requested URL parameters or any other custom
        logic you want to implement.
        """
        # Retrieve the tag slug from the URL parameter
        tag_slug = self.kwargs.get("tag_slug")

        if tag_slug:
            # Get the tag object based on the slug
            tag = get_object_or_404(Tag, slug=tag_slug)
            # Filter the posts based on the specified tag
            queryset = Post.published.filter(tags__in=[tag])
        else:
            # If no tag is specified, retrieve all published posts
            queryset = Post.published.all()

        return queryset


# a function-based view for handling forms
def post_share(request, post_id):
    """
    Takes the request obj and the post_id variable as params
    to handle both HTTP methods GET and POST where
    in case of the latter it'll send an email
    """

    # Retrieve post by its id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == "POST":  # POST method
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data  # a dict of form fields and their values
            # In case of failing is_valid(), cleaned_data attribute still got
            # valid fields
            # ... send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you to read " f"{post.title}"
            message = (
                f"Read {post.title} at {post_url}\n\n"
                + f"{cd['name']}'s comments: {cd['comments']}"
            )
            send_mail(subject, message, "couzhei@gmail.com", [cd["to"]])
            sent = True

    # elif request.method == "GET":
    else:
        form = EmailPostForm()  # GET method

    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


def post_detail(
    request,
    # id, # after deciding to make our URLs more SEO-friendly
    year,
    month,
    day,
    post,
):
    # try:
    #     post = Post.published.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404("No such post found.")
    # or
    post = get_object_or_404(  # from django.shortcuts
        Post,
        # id=id,
        slug=post,
        published_on__year=year,
        published_on__month=month,
        published_on__day=day,
        status=Post.Status.PUBLISHED,
    )

    # List of active comments for this post
    comments = post.comments.filter(active=True)  # type: ignore
    # Form for users to comment
    form = CommentForm()

    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "form": form,
        },
    )


# CV view for post_detail
class PostDetailView(DetailView):
    pass


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED,
    )

    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)

    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()

    return render(
        request,
        "blog/post/comment.html",
        {
            "post": post,
            "form": form,
            "comment": comment,
        },
    )

templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}
    Add a comment
{% endblock %}
{% block content %}
    {% if comment %}
        <h2>
            Your comment has been added.
        </h2>
        <p>
            <a href="{{ post.get_absolute_url }}">Back to the post</a>
        </p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}
    {{ post.title }}
{% endblock title %}
{% block content %}
    <h1>
        {{ post.title }}
    </h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body | linebreaks }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">Share this post</a>
    </p>
    <p class="tags">
        Tags: {{ post.tags.all|join:", " }}
    </p>
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
        <!-- This one is good for thing(s) -->
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>
            There are no comments.
        </p>
    {% endfor %}
    <!-- Now to add the comment form -->
    {% include "blog/post/includes/comment_form.html" %}
{% endblock content %}

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}
    List of Published Articles
{% endblock title %}
{% block content %}
    <h1>
        List of Published Articles
    </h1>
    <!-- In case of calling all the posts related to a single tag -->
    {% if tag %}
        <h2>
            Posts tagged with "{{ tag.name }}"
        </h2>
    {% endif %}
    {% for post in posts %}
        {% comment %}use comm snippet for these comments{% endcomment %}
        <!--and com for these -->
        <h2>
            {% comment %} <!-- <a href="{% url 'blog:post_detail' post.id %}"> replaced by--> {% endcomment %}
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        {% if not tag %}
            <p class="tags">
                Tags: <!--{{ post.tags.all|join:", " }} This is fine,
but it doesn't allow users to click on a tag to view all posts 
related to that tag. We add that functionality with a link-->
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_li1st_by_tag' tag.slug %}">{{ tag.name }}</a>
                    {% if not forloop.last %}
                        ,
                    {% endif %}
                {% endfor %}
            </p>
        {% endif %}
        <!--whoa the above join looks mysterious -->
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    <!-- In order to keep pagination working
    we have to use the right page object that is passed
    to the template. By default ListView generic view
    passes the page requested in a variable called page_obj -->
    {% include "pagination.html" with page=posts %}
    {% comment %} {% include "pagination.html" with page=page_obj %} {% endcomment %}
{% endblock content %}

templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}
    Share a post with your friends!
{% endblock title %}
<!-- This is a template showing both the form to share a post via email and,
to display a success message when the email has been sent.-->
{% block content %}
    {% if sent %}
        <!-- we differentiate between both cases using this condition -->
        <h1>
            E-mail succussfully sent.
        </h1>
        <p>
            "{{ post.title }}" was succussfully sent to {{ form.cleaned_data.to }}.
        </p>
        <a href="{{ post.get_absolute_url }}">Back to the post</a>
    {% else %}
        <h1>
            Share "{{ post.title }}" by e-mail
        </h1>
        <form method="post">
            {% comment %} {{ form.as_p }} {% endcomment %}
            {% for field in form %}
                <div>
                    {{ field.label_tag }} {{ field }} {{ field.errors }}
                </div>
            {% endfor %}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
            <input type="button"
                   value="Cancel"
                   onclick="location.href='{{ post.get_absolute_url }} ';" />
            <!-- I made a button to get back to the page it's going to share with their friend -->
        </form>
    {% endif %}
{% endblock content %}